INSERT INTO `Productos` (`Id_producto`, `Nombre`, `Descripcion`, `Precio`, `Stock`, `Categoria`) 
VALUES
(1, 'Laptop X1000', 'Potente laptop con procesador de última generación', 999.99, 50, 'Electrónicos'),
(2, 'Camiseta Deportiva', 'Camiseta transpirable para actividades deportivas', 29.99, 100, 'Ropa'),
(3, 'Aspiradora Inteligente', 'Aspiradora con tecnología de limpieza inteligente', 149.99, 30, 'Electrodomésticos'),
(4, 'Libro: Aventuras en el Espacio', 'Novela de ciencia ficción sobre exploración espacial', 19.99, 80, 'Libros'),
(5, 'Set de Construcción', 'Juego de construcción para niños', 49.99, 120, 'Juguetes'),
(6, 'Smartphone ZPro', 'Teléfono inteligente con cámara de alta resolución', 599.99, 60, 'Electrónicos'),
(7, 'Jeans Clásicos', 'Jeans de estilo clásico y cómodo', 39.99, 90, 'Ropa'),
(8, 'Cafetera Automática', 'Cafetera que prepara café automáticamente', 79.99, 40, 'Electrodomésticos'),
(9, 'Libro de Cocina Gourmet', 'Recetas gourmet de chefs famosos', 29.99, 75, 'Libros'),
(10, 'Juego de Mesa Estratégico', 'Juego de mesa para desarrollar habilidades estratégicas', 34.99, 50, 'Juguetes'),
(11, 'Auriculares Inalámbricos', 'Auriculares con cancelación de ruido', 129.99, 25, 'Electrónicos'),
(12, 'Camisa Elegante', 'Camisa elegante para ocasiones especiales', 49.99, 70, 'Ropa'),
(13, 'Robot Asistente', 'Robot inteligente para ayudar en tareas del hogar', 299.99, 20, 'Electrodomésticos'),
(14, 'Libro de Misterio', 'Novela de misterio y suspense', 14.99, 100, 'Libros'),
(15, 'Juguetes Educativos', 'Set de juguetes educativos para niños pequeños', 19.99, 80, 'Juguetes'),
(16, 'Televisor 4K', 'Televisor con calidad de imagen 4K', 699.99, 30, 'Electrónicos'),
(17, 'Chaqueta Deportiva', 'Chaqueta para actividades al aire libre', 59.99, 60, 'Ropa'),
(18, 'Licuadora Multifunción', 'Licuadora con múltiples funciones', 89.99, 45, 'Electrodomésticos'),
(19, 'Libro de Historia Antigua', 'Exploración de civilizaciones antiguas', 24.99, 110, 'Libros'),
(20, 'Rompecabezas 3D', 'Rompecabezas tridimensional desafiante', 39.99, 75, 'Juguetes'),
(21, 'Tablet Avanzada', 'Tablet con pantalla de alta resolución', 349.99, 40, 'Electrónicos'),
(22, 'Sudadera con Capucha', 'Sudadera cómoda con capucha ajustable', 45.99, 80, 'Ropa'),
(23, 'Asador Eléctrico', 'Asador eléctrico para parrilladas en interiores', 129.99, 35, 'Electrodomésticos'),
(24, 'Colección de Poesía', 'Antología de poesía contemporánea', 18.99, 90, 'Libros'),
(25, 'Bloques de Construcción', 'Bloques para construcción creativa', 29.99, 60, 'Juguetes'),
(26, 'Reloj Inteligente', 'Reloj con funciones inteligentes y monitor de actividad', 159.99, 50, 'Electrónicos'),
(27, 'Blusa Casual', 'Blusa ligera y casual para cualquier ocasión', 24.99, 70, 'Ropa'),
(28, 'Horno de Convección', 'Horno con tecnología de convección para cocina uniforme', 179.99, 25, 'Electrodomésticos'),
(29, 'Libro de Ciencia Ficción', 'Historias fascinantes de futuros imaginarios', 22.99, 85, 'Libros'),
(30, 'Pelota de Fútbol', 'Pelota oficial para partidos y entrenamientos', 19.99, 100, 'Juguetes'),
(31, 'Altavoces Bluetooth', 'Altavoces inalámbricos con sonido de alta calidad', 79.99, 40, 'Electrónicos'),
(32, 'Vestido Elegante', 'Vestido elegante para eventos formales', 69.99, 30, 'Ropa'),
(33, 'Robot de Cocina', 'Robot multifunción para preparar diversas recetas', 249.99, 15, 'Electrodomésticos'),
(34, 'Libro de Poesía Clásica', 'Selección de poesía de autores clásicos', 16.99, 95, 'Libros'),
(35, 'Juego de Construcción Magnético', 'Construcción magnética para niños creativos', 44.99, 70, 'Juguetes'),
(36, 'Proyector HD', 'Proyector de alta definición para entretenimiento en casa', 299.99, 20, 'Electrónicos'),
(37, 'Abrigo de Invierno', 'Abrigo resistente al frío para invierno', 89.99, 50, 'Ropa'),
(38, 'Batidora de Mano', 'Batidora portátil para mezclas rápidas', 49.99, 55, 'Electrodomésticos'),
(39, 'Libro de Biografías', 'Historias fascinantes de personajes históricos', 26.99, 80, 'Libros'),
(40, 'Juego Educativo de Ciencias', 'Kit educativo para aprender sobre ciencias', 32.99, 65, 'Juguetes'),
(41, 'Cámara DSLR', 'Cámara digital de alta calidad para fotografía profesional', 899.99, 15, 'Electrónicos'),
(42, 'Bufanda de Lana', 'Bufanda suave y abrigada para el invierno', 15.99, 120, 'Ropa'),
(43, 'Licuadora de Jugo', 'Licuadora especializada para jugos frescos', 69.99, 35, 'Electrodomésticos'),
(44, 'Colección de Cuentos Cortos', 'Antología de cuentos breves de diversos géneros', 21.99, 75, 'Libros'),
(45, 'Kit de Arte para Niños', 'Set completo de materiales para actividades artísticas', 27.99, 90, 'Juguetes'),
(46, 'Smartwatch Deportivo', 'Reloj inteligente con funciones específicas para deportes', 129.99, 40, 'Electrónicos'),
(47, 'Pantalones Casual', 'Pantalones cómodos y versátiles para uso diario', 34.99, 85, 'Ropa'),
(48, 'Tostadora de Pan', 'Tostadora con múltiples configuraciones para un tostado perfecto', 39.99, 50, 'Electrodomésticos'),
(49, 'Libro de Filosofía', 'Exploración de ideas filosóficas a lo largo de la historia', 28.99, 60, 'Libros'),
(50, 'Bloques de Construcción Gigantes', 'Bloques grandes para construcciones creativas a gran escala', 59.99, 40, 'Juguetes'),
(51, 'Altavoz Inteligente', 'Altavoz con asistente de voz integrado para controlar tu hogar', 119.99, 25, 'Electrónicos'),
(52, 'Vestido de Noche', 'Vestido elegante para ocasiones especiales de noche', 79.99, 30, 'Ropa'),
(53, 'Cafetera Espresso', 'Máquina de espresso para disfrutar de café gourmet en casa', 149.99, 20, 'Electrodomésticos'),
(54, 'Libro de Arte Moderno', 'Exploración de movimientos artísticos del siglo XX', 31.99, 50, 'Libros'),
(55, 'Juego de Herramientas para Niños', 'Kit de herramientas seguras para aprender a construir', 19.99, 80, 'Juguetes'),
(56, 'Monitor Curvo 27"', 'Monitor de computadora con pantalla curva para una experiencia inmersiva', 349.99, 15, 'Electrónicos'),
(57, 'Chaleco Casual', 'Chaleco ligero y moderno para complementar tu estilo', 28.99, 70, 'Ropa'),
(58, 'Exprimidor de Cítricos', 'Exprimidor eléctrico para preparar jugos frescos de naranja y limón', 34.99, 35, 'Electrodomésticos'),
(59, 'Libro de Poesía Romántica', 'Selección de poemas románticos de diversos autores', 17.99, 95, 'Libros'),
(60, 'Juego de Construcción de Vehículos', 'Construye tu propio conjunto de vehículos con piezas modulares', 49.99, 60, 'Juguetes');